version: '3'

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "${PORT}:${PORT}"
     # - "${DB_PORT}:${DB_PORT}"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://${DB_USER}:${DB_PASSWORD}@${HOST}/${DB_NAME}
    depends_on:
      - db


  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
